# Generated by Selenium IDE
from selenium_controller.auto_auth import AutoAuth
from selenium_controller.auto_upload import AutoUpload


class TestTest():
  
  def test_test(self):
    # Test name: test
    # Step # | name | target | value
    # 1 | open | /calendar/view/week |
    AutoAuth().init()
    AutoUpload().upload()
